[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r server/requirements.txt"
]
cacheDirectories = ["/opt/venv"]

[start]
cmd = "cd server && /opt/venv/bin/flask db upgrade && /opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --workers 4"

[variables]
VIRTUAL_ENV = "/opt/venv"
PATH = "/opt/venv/bin:$PATH"
