# Nixpacks Configuration for Railway
# This file tells Railway how to build and deploy the backend

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "cd server",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd server",
  "flask db upgrade"
]

[start]
cmd = "cd server && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
