databases:
  - name: mealy-postgres
    databaseName: mealy
    user: mealy
    plan: free

services:
  # Frontend Static Site (Free)
  - type: web
    name: mealy-frontend
    runtime: static
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_URL
        value: https://mealy-backend.onrender.com
