services:
  # Backend API Service
  - type: web
    name: mealy-backend
    env: python
    region: singapore
    buildCommand: |
      cd server
      python -m venv /opt/render/project/.venv
      . /opt/render/project/.venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd server
      . /opt/render/project/.venv/bin/activate
      flask db upgrade
      gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: mealy-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False

  # Frontend Service (React)
  - type: web
    name: mealy-frontend
    env: static
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: mealy-backend
          envVarKey: RENDER_EXTERNAL_URL

# Database
databases:
  - name: mealy-db
    databaseName: mealy
    user: mealy_user
    region: singapore
