name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'client/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'client/**' ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint --if-present
        
      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false
        
      - name: Build React app
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: client/build/
          retention-days: 7